### ISSUE TITLE
Unable to establish MAVLink communication Apsync.

### ISSUE THREAD

**Issue by rbachtell** [mtbsteve/redtail#5]
This is in response to the comment I left in the wrong place.  First of all I thought I was adequately specific and detailed in my comment but the short story is that I have refreshed and subsequently loaded Apsync six times following the wiki accurately and am unable to establish communication through the serial port on the Development board.  All components are known to work properly and connection is accurate.  My comment in the wrong place detailed that I have been successfully using Apsync since the beginning of the Apsync project and all equipment has previously been tested.

**Comment by mtbsteve** [comment]
Randy, it’s not possible for me to identify the issue w/o further information about what you have installed and what wiki you are following. The Redtail wiki instructions assume you have a working APsync layer installed upfront- it’s not included in this repo.  Redtail doesn’t change nor overwrite anything related to APsync. 

Also, It doesn’t matter what version of APsync - You may use my version the original version of peterbarker or your version of APsync you had up and running before and you are familiar with. As a bare minimum the AP must work and you must be able to communicate with the FC through mavproxy:

# ssh into device
ssh apsync@10.0.1.128

# Check "screen -list" includes mavlink-router, DataFlashLogger, cherrypy:
screen -list

screen -list
There are screens on:
	1754.cherrypy	(12/08/2017 03:00:54 AM)	(Detached)
	1733.DataFlashLogger	(12/08/2017 03:00:54 AM)	(Detached)
	1704.mavlink-router	(12/08/2017 03:00:54 AM)	(Detached)

# Check APWeb is running:
sudo screen -list
There is a screen on:
	1765.apweb	(12/08/2017 03:00:54 AM)	(Detached)

# ensure mavproxy starts on the apsync image:
mavproxy.py --master :14550 --source-system=56
# make sure you can fetch parameters:
param fetch
param status

If this doesn’t work, check your env, in particular the setting for the telemetry serial port. (I assume you have checked the wiring between the serial port and the Pixhawk already). If you are using the J17 connector on the Nvidia TX2 development board
then  edit the config.env file and set 
export TELEM_SERIAL_PORT=/dev/ttyTHS2

If it still doesn’t work, either your hardware has an issue or something in your installation of mavlink got screwed.

If it is working, THEN you can continue with installing the Redtail components, ROS, the DNN’s etc as explained in the wiki of this repo.

**Comment by rbachtell** [comment]
Sorry i haven’t been more clear.  I have been using the apsync install from your repo (Nvidia_JTX2_JP42/Ubuntu/1_create_base_image_tx2_JP42.txt
)  I understood from the code and instructions that you made modifications to work with JetPack 4.2.2 so I followed your instructions.  I have never gone past apsync install as it has not been functional, my reference to redtail was your repo apsync page.  I can not ssh into the device after several clean JetPack installs following your instructions.  My reference to working systems was to previous TX1 installs using Peter and Randy’s work with apsync and openkai. I have two TX1’s loaded and working with apsync and use those as reference to check my work and AP function.

Thanks for the help,
RB

**Comment by mtbsteve** [comment]
OK - if you can't even ssh into the TX2, your problem is within the very first installation steps. 
What is the error message when you run `ssh apsync@10.0.1.128` from a connected client PC?
In order to help, can you provide the following infos:
1. L4T release: 
Run:  `head -n 1 /etc/nv_tegra_release` and paste the output.

2. User setup: TX2 should boot and automatically logon as apsync. If this is not the case, let me know the following infos:
- Run: `cat /etc/hosts` and paste the output.
- Run: `groups apsync` and paste the output
- Run: `cat /etc/gdm3/custom.conf` and paste the output.

3. Network setup: The TX2 should initiate an WIFI access point with the SSID ardupilot and the password ardupilot. If you can't see the AP from another computer and if you cannot connect to the ardupilot network, provide the following infos:
- Run: `nmcli device wifi` and paste the output
- Run: `cat /etc/modprobe.d/bcmdhd.conf` and paste the output
- Run: `cat /home/apsync/.profile | grep nmcli` and paste the output

4. ssh:
- Connect to the ardupilot AP from another computer and Run `ssh apsync@10.0.1.128`
When you try to connect for the first time, you will get a Authenticity warning. Just confirm to continue with `yes`

**Comment by rbachtell** [comment]
Thanks Steve,  TX2 boots and auto logs on as apsync.  TX2 does initiate WiFi access point “ardupilot” and the web app comes up but does not get heartbeat.

this is the message upon ssh from my Mac
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:g3QthPoq8Ji/TINXYqjWc0LnrqwkBRYIhnPkntbV0H4.
Please contact your system administrator.
Add correct host key in /Users/rdb/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/rdb/.ssh/known_hosts:2
ECDSA host key for 10.0.1.128 has changed and you have requested strict checking.
Host key verification failed.

here are the results:
IN-USE  SSID       MODE   CHAN  RATE      SIGNAL  BARS  SECURITY  
*       ardupilot  Infra  1     0 Mbit/s  0       ____  WPA1 WPA2

apsync@apsync:~$ cat /etc/modprobe.d/bcmdhd.conf
install bcmdhd test -d /lib/firmware/brcm && /sbin/modprobe --ignore-install bcmdhd
options bcmdhd op_mode=2


apsync@apsync:~$ cat /home/apsync/.profile | grep nmcli
if nmcli d | grep ardupilot; then sleep 1; else nmcli connection up ardupilot; fi

**Comment by mtbsteve** [comment]
Ha that’s an easy one. That’s basic Linux networking and has nothing to do with APsync. Google knows that problem very well 😊
Here is a solution:
https://stackoverflow.com/questions/20840012/ssh-remote-host-identification-has-changed

Reason: you connected your Mac with an AP “ardupilot” before. Now you’re trying it again, but since it’s a different system image the host key is different and doesn’t match the one stored on your Mac. ssh sees a potential security threat and blocks access.

**Comment by mtbsteve** [comment]
just to add - thanks for sharing the other information. That all looks good. So once you got the ssh stuff working we can look at mavlink.

**Comment by rbachtell** [comment]
OK on another fresh build I am able to connect with QGC and all FC data is there.  No love with apweb, will not hook up on any device.  I am able to ssh in with my Ubuntu machine and I get no sockets found with the screen -list commands.

**Comment by rbachtell** [comment]
apsync@apsync:~$ mavproxy.py --master :14550 --source-system=56
Connect :14550 source_system=56
Running script (/home/apsync/.mavinit.scr)
Running script /home/apsync/.mavinit.scr
-> set moddebug 3
Log Directory: 
Telemetry log: mav.tlog
Waiting for heartbeat from :14550
MAV> link 1 down

**Comment by kellyschrock** [comment]
Just noticed the "link 1 down" message there. You might check to make sure
mavproxy isn't crashing. If you see one or more crash-log files in the
directory after getting this message, that's how you know it did. I have
gotten this with SITL (which uses mavproxy) in the past.

**Comment by mtbsteve** [comment]
OK Randy lets take a step by step approach.
1. can you ssh in now from any other machine including your Mac?
If not, you need to run on the respective machine `ssh-keygen -R 10.0.1.128` as mentioned above in order to remove the previous host key stored eg on your Mac.

2. On the TX2, please run: `head -n 1 /etc/nv_tegra_release` and paste the output.

3. On the TX2, what does `screen -list`  display? You should get:
```
apsync@apsync:~$ screen -list
There are screens on:
	5959.cherrypy	(12.03.2020 08:40:23)	(Detached)
	5870.DataFlashLogger	(12.03.2020 08:40:23)	(Detached)
	5759.mavlink-router	(12.03.2020 08:40:23)	(Detached)
3 Sockets in /run/screen/S-apsync.
```
If can not see those 3 screens, please run `cat /etc/rc.local ` and paste the output.

4. Check for apweb process: on the TX2, please run `ps -ef | grep [w]eb_server` and paste the output.

5. mavlink:
Can you please run: 
`ps -ef | grep [r]outerd` and paste the result, then run:
`head -n 20 ~/start_mavlink-router/screenlog.0` and paste the output.

**Comment by rbachtell** [comment]
Here it is, I am able to connect udp to QGround Control and I can ssh in with my Mac and my Ubuntu machine but the results on the TX2 are not so good.

apsync@apsync:~$ head -n 1 /etc/nv_tegra_release
# R32 (release), REVISION: 2.1, GCID: 16294929, BOARD: t186ref, EABI: aarch64, DATE: Tue Aug 13 04:45:36 UTC 2019

apsync@apsync:~$ screen -list
No Sockets found in /run/screen/S-apsync.

apsync@apsync:~$ cat /etc/rc.local
apsync@apsync:~$ 

apsync@apsync:~$ ps -ef | grep [w]eb_server
apsync@apsync:~$ ps -ef | grep [r]outerd
apsync@apsync:~$ head -n 20 ~/start_mavlink-router/screenlog.0
head: cannot open '/home/apsync/start_mavlink-router/screenlog.0' for reading: No such file or directory

**Comment by mtbsteve** [comment]
ok thanks. None of the mandatory apsync processes are running after startup on your TX2, including mavlink-router. That explains why mavproxy is not working since it cant establish the connection (link 1 down). Since /etc/rc.local is empty which would initiate all processes at boot, something fundamental must have gone south during the basic installation steps. However /etc/rc.local exists, that indicates you had completed up to line 51 of the install script.

To resolve, please logon to the TX2 as apsync user and EXACTLY follow line by line the steps listed in the install instructions from line 55 onwards:  
https://github.com/mtbsteve/companion/blob/7e150e238f933a2699ec20f1d53f998a40f4e371/Nvidia_JTX2_JP42/Ubuntu/1_create_base_image_tx2_JP42.txt#L55

Execute each line one by one  **manually** and check for any potential error messages. As written in the instructions at line 68, set the TELEM_SERIAL_PORT=/dev/ttyTHS2 for the development board. (by default its set to ttyTHS1 for the Auvidea carrier board).

Run through all the listed steps and then retest. In case there appear any errors during install, pls stop and post the error here.

**Comment by rbachtell** [comment]
I will do that as soon as I have a chance but how do you explain that I can connect to Apsync on the ArduPilot hot spot and have MAVLink communication with UDP on QGroundControl?   

Randy Bachtell

**Comment by rbachtell** [comment]
OK, I did as you suggested and reinstalled from line 55.  No error messages only the occasional “Requirement already satisfied or an indication that the package was already installed.  Same situation exists as it has from the start.  Another strange thing is that I can connect via UDP with qgroundcontrol on my Ubuntu machine and have full communication with the FC.  i can ssh in with any system but apweb doesn’t connect or even load and I can’t connect with mission planner on windows or with qgroundcontrol on my Mac.
BTW I have followed the install steps exactly every time I’ve done it.

**Comment by rbachtell** [comment]
I did find this warning in mavlink-router install

src/mavlink-router/endpoint.cpp:768:31: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]

**Comment by mtbsteve** [comment]
﻿you can ignore warnings. 
Any entries now in /etc/rc.local?


Von meinem iPhone gesendet

>> Am 12.03.2020 um 19:45 schrieb rbachtell <notifications@github.com>:
> ﻿
> I did find this warning in mavlink-router install
> 
> src/mavlink-router/endpoint.cpp:768:31: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
>

**Comment by rbachtell** [comment]
still nothing.  Have you heard from anyone that successfully installed apsync from your repo?  I can’t think of anything I could have done to cause this, I have have re-done this multiple times on two TX2’s on two different carrier boards with exactly the same results every time.

**Comment by mtbsteve** [comment]
If there are no entries in /etc/rc.local,  it’s an indication that every single install  script fails. They are more or less simple shell scripts to copy  some files from the github directory into your apsync home directory, and finally add one line to/etc/rc.local to autostart the respective service during boot. 

The install scripts are mostly 1:1 the original files from peterbarker and have been used by many people. I ran those scripts at least half a dozen of times myself.  
It’s not possible for me to remote-debug what’s wrong with your setup w/o having direct access to your system. 

I suggest you take one service such as eg mavlink-router (which is 100% peters original file), run it line by line and check the results on your TX2 file system. 

time sudo -E ./setup_mavlink-router

Maybe it is a permission problem. 
You may post the content of the directory 
ls -l /home/apsync/start_mavlink-router

here for me to take a look 

Von meinem iPhone gesendet

> Am 12.03.2020 um 21:40 schrieb rbachtell <notifications@github.com>:
> 
> ﻿
> still nothing. Have you heard from anyone that successfully installed apsync from your repo? I can’t think of anything I could have done to cause this, I have have re-done this multiple times on two TX2’s on two different carrier boards with exactly the same results every time.
>

**Comment by rbachtell** [comment]
Sorry to take up so much of your time, I too have run Peters scripts multiple time successfully.  Here is the list from my TX2

apsync@apsync:~/GitHub/companion/Nvidia_JTX2_JP42/Ubuntu$ ls -I/home/apsync/start_mavlink-router
1_create_base_image_tx2_JP42.txt  install_apweb
2_install_packages.sh             install_niceties
3_wifi_access_point_JP42.sh       install_pymavlink
4_setup_log_rotation              remove-unattended-upgrades
5_setup_mavproxy.sh               set-hostname
6_setup_gstreamer.sh              setup_APStreamline.sh
7_dflogger.sh                     setup_mavlink-router
8_setup_cmavnode.sh               setup-video-streaming
autostart_apweb.sh                start_apweb.sh
change-autologin-user_1804.sh     start_udp_stream
clean-for-imaging                 switch_AP_client_mode.sh
config.env                        TX2-testing.txt
ensure_rc_local.sh                upload_to_ardupilot.org.sh

Thanks for all your help.  It looks like it’s time to switch to my other hobby and get back on my bikes.

**Comment by mtbsteve** [comment]
Thanks. Thats the content of your `/GitHub/companion/Nvidia_JTX2_JP42/Ubuntu` directory. There was a typo in your` ls -l` command. I wanted to check the content of the directory `/home/apsync/start_mavlink-router` to see if at least something got installed on your machine.

**Comment by rbachtell** [comment]
Yep, my mistake.  Here it is, I really think that everything is there and always has been.  Back at the start of this process I actually had a build that worked until I started the redtail install and screwed it up.  Since then i have had pieces of the puzzle work but never all, the last few builds I have nothing working.

apsync@apsync:~$ ls -l /home/apsync/start_mavlink-router 
total 972
-rwxr-xr-x 1 apsync apsync    173 Mar 12 15:51 autostart_mavlink-router.sh
-rw-r--r-- 1 apsync apsync   3779 Mar 12 15:51 mavlink-router.conf
-rwxr-xr-x 1 apsync apsync 978256 Mar 12 15:52 mavlink-routerd
-rw-r--r-- 1 apsync apsync    563 Mar 13 05:24 screenlog.0
-rw-r--r-- 1 apsync apsync      0 Mar 13 05:24 start_mavlink-router.log
-rwxr-xr-x 1 apsync apsync     69 Mar 12 15:51 start_mavlink-router.sh

**Comment by mtbsteve** [comment]
Much better. As it looks you got now a screenlog.0 file which indicates some activity. Coming back to what I raised before, could you run on the TX2 :
`screen -list `and paste the output
`cat /etc/rc.local` and paste the output.
`ps -ef | grep [r]outerd` and paste the result, then run:
`head -n 20 ~/start_mavlink-router/screenlog.0` and paste the output.

**Comment by rbachtell** [comment]
Same as before

apsync@apsync:~$ screen -list
No Sockets found in /run/screen/S-apsync.

apsync@apsync:~$ cat /etc/rc.local
apsync@apsync:~$ ps -ef | grep [r]outerd
apsync@apsync:~$ head -n 20 ~/start_mavlink-router/screenlog.0
head: cannot open '/home/apsync/start_mavlink-router/screenlog.0' for reading: No such file or directory
apsync@apsync:~$

**Comment by rbachtell** [comment]
I get an error on the TX2 startup screen “Failed to start /etc/rc.local. Compatibility

**Comment by rbachtell** [comment]
I FIXED IT!!!

Turns out the /etc/rc.local was blank so I copied the file in from my TX1/OpenKai and edited out the line to start openkai. Works perfectly 

Randy Bachtell

**Comment by mtbsteve** [comment]
Good. Thats what I said - w/o the services launched from /etc/rc.local it simply cannot work. I am closing this issue.

**Comment by rbachtell** [comment]
That’s all well and good Steve but how did the file remain empty on every clean flash and install?  I’m going to re-flash one of the TX2’s today and see if the problem returns. I clean installed on both TX2’s at least 6 times and finally had to manually make the rc.local file. I’ll let you know my results. 

Randy Bachtell

**Comment by mtbsteve** [comment]
Again, this is a problem with your setup. The entries in /etc/rc.local are created by the very last line of the respective install scripts. You can run the pearl statement by hand to find out why’s not working on your machine  It’s 100% the original code which I forked from Peter‘s git. 
Sorry but there is nothing what I can do. 

Von meinem iPhone gesendet

> Am 14.03.2020 um 14:43 schrieb rbachtell <notifications@github.com>:
> 
> ﻿
> That’s all well and good Steve but how did the file remain empty on every clean flash and install? I’m going to re-flash one of the TX2’s today and see if the problem returns. I clean installed on both TX2’s at least 6 times and finally had to manually make the rc.local file. I’ll let you know my results. 
> 
> Randy Bachtell
> Sent from my iPhone
>
