### ISSUE TITLE
Runs on Jetson Nano JetPack 4.4 (mostly)

### ISSUE THREAD

**Issue by zoombinis** [mtbsteve/redtail#9]
Hi,

I successfully built this repo for JetPack 4.4 (specifically the stereo_dnn portion of it) after only having to tweak a few OpenCV constants and adding a missing fstream include (nothing major).

It all runs great in rviz if I roslaunch the stereo_dnn before any `*.plan` file exists, but if I run a second time and it tries to load the cached `*.plan` file I can get a couple different errors (randomly it seems)

>TRT WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
double free or corruption (out)
[stereo_dnn_ros-1] process has died [pid 9377, exit code -6, cmd /home/jet/catkin_ws/devel/lib/stereo_dnn_ros/stereo_dnn_ros_node __name:=stereo_dnn_ros __log:=/home/jet/.ros/log/e2e0a3f8-1363-11eb-a1aa-00044be527f3/stereo_dnn_ros-1.log].
log file: /home/jet/.ros/log/e2e0a3f8-1363-11eb-a1aa-00044be527f3/stereo_dnn_ros-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Or I'll get the same error except it will also specify:

> malloc()

Is this maybe an incompatibility with tensorRt version that comes with jetpack 4.4 or something you've seen before? I am using `ap_zed_resnet18_2D_fp16.launch` and no modifications other than the camera topic names and commenting out the zed stuff since I am using axis cameras.

**Comment by mtbsteve** [comment]
sorry for the late reply. Frankly I have not tried to run it on Jetpack 4.4 yet. I am still on 4.2 :-)
What tweaks did you do in order to get it running?

**Comment by mtbsteve** [comment]
@zoombinis ok I just adopted the code to Jetpack 4.4 and I can reproduce your problem.
That error does not occur with JP 4.2. Yes it could be an incompatibility with TRT 7.1.3
I tried to set MALLOC_CHECK_ to 2 in order to workaround it but this causes now a memory corruption error.
But my c++ skills are not good enough to trace it further down I am afraid..

**Comment by kumarvarma1** [comment]
Any update for jetpack 4.4 ?

**Comment by mtbsteve** [comment]
No. If you want to use Redtail, you will need to stay with 4.2 I am afraid. Or try to port it to the newer Jetpack versions.

**Comment by Ashish-Github193** [comment]
Hi @zoombinis  , I'm using jetpack 4..4 and opencv 4.1.1 so its give me an error 
![133597288-d474f3c7-2a3e-4cc3-82b9-18f0ffc1abf6](https://user-images.githubusercontent.com/79639825/134163006-3a13483f-5106-4ae6-8a70-35d0d3342e61.jpeg)
Could you please tell me What changes you made with opencv to make it work?🙏
